### ISSUE TITLE
Generation of site information and javadoc does not work anymore

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djunits#23]
The generation of the site has not been working for quite a while now. The site and javadoc should be generated using a job on one of the Delft servers.

**Comment by averbraeck** [comment]
There are a number of issues that need to be updated:

1) Lots of javadoc errors... They are **not caught*** when we deploy a version with github actions. This is, of course, wrong... Therefore, the github actions should try to build a site:

```yaml
    - name: Build with Maven and check if site building works
      run: mvn clean site --file pom.xml

    - name: Build with Maven and test if signing works
      run: mvn clean package -P release --file pom.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
```
