### ISSUE TITLE
Update djunits to Java-17

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/djunits#28]
The current Java version for djunits is Java-11. Prime Oracle support for Java-11 ended 15 October 2024 (see https://www.oracle.com/java/technologies/java-se-support-roadmap.html). Some other vendors still create new releases (see e.g., https://adoptium.net/support/). It cannot be guaranteed, however, that Java-11 contains (security) bug fixes for all OpenJDK vendors from now on. Therefore, new releases from now onward will be for Java-17 and up.

This has as an additional advantage that new features such as the `record`, the expanded `switch`, `instanceof` casting, and numerous updates in the libraries can be used as well.

**Comment by averbraeck** [comment]
The github action workflow has to be adapted to use Java-17:

```yaml
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java 17 for publishing to Maven Central Repository
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        settings-path: ${{ github.workspace }} # location for the settings.xml file
```
